modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_repo_url}/issues"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayURL = "${mod_repo_url}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# Load after FTB Ultimine so the new shapes come after the built-in ones in the shape menu.
# Needed on BOTH sides: client and server must have the same shape list.
[[dependencies.${mod_id}]]
modId = "ftbultimine"
type = "required"
versionRange = "${ftb_ultimine_version_range}"
ordering = "AFTER"
side = "BOTH"
